### ISSUE TITLE
Support channel passwords

### ISSUE THREAD

**Issue by jkramer** [zoffixznet/perl6-IRC-Client#18]
Currently only server passwords are supported, but channels can have their own password each which has to be sent along with the /join command. It would be nice to make the channel list in the constructor a hash ("#channel" => "channelpw").

**Comment by zoffixznet** [comment]
Done. Channels can now be specified either as Str or as a Pair where the key is the channel and value is the password for it:

```perl6
:channels('#perl6bot', '#zofbot', '#myown' => 's3cret')
```
