### ISSUE TITLE
Allow alternate nicknames for bots

### ISSUE THREAD

**Issue by MasterDuke17** [zoffixznet/perl6-IRC-Client#22]
I believe there was some discussion on IRC, but I don't remember the conclusion. It would let people use things like e.g., bench for benchable, bisect for bisectable. You could always implement it by hand with irc-all(), but that seems like overkill. Maybe it would be as simple as turning this:
`if $e.text.subst-mutate: /^ $nick <[,:]> \s* /, '' {`
into this:
`if $e.text.subst-mutate: /^ @nicks <[,:]> \s* /, '' {`

**Comment by zoffixznet** [comment]
Added in version 3.006001 as `:alias` argument. It can take a list of Str or Regex and functions as an alias to the currently used nick:

```
    .run with IRC::Client.new:
        :nick<Foo>
        :alias('bar', /meow [able]?/);

    ##
   # Foo, do stuff
   # bar, do stuff
   # meow, do stuff
   # meowable, do stuff
```

**Comment by AlexDaniel** [comment]
Amazing! Thank you
