### ISSUE TITLE
｢.text｣ does not contain the full message, let's have ｢.full-text｣ ?

### ISSUE THREAD

**Issue by AlexDaniel** [zoffixznet/perl6-IRC-Client#25]
If somebody writes a message like ``foobot, hello!`` then you can only see ``hello!``. While it makes sense, sometimes it is required to get a full message ``foobot, hello!``, and I don't see any way to do it currently. Perhaps another attribute called ``$full-text`` can be added?

**Comment by zoffixznet** [comment]
You can obtain it from [`.args`](https://github.com/zoffixznet/perl6-IRC-Client/blob/master/docs/03-method-reference.md#args)

**Comment by AlexDaniel** [comment]
Yea, that works! Thanks!
