### ISSUE TITLE
And all IRC Commands

### ISSUE THREAD

**Issue by Skarsnik** [zoffixznet/perl6-IRC-Client#3]
It's in the title :)

**Comment by zoffixznet** [comment]
Yeah, I plan to flesh this thing out over Christmas/New Years holidays and add all IRC commands, including password support

**Comment by zoffixznet** [comment]
server password is now a thing: https://github.com/zoffixznet/perl6-IRC-Client#password

**Comment by zoffixznet** [comment]
Will be added in the rewrite.
