### ISSUE TITLE
irc-XXX is not valid perl 6 method name

### ISSUE THREAD

**Issue by AlexDaniel** [zoffixznet/perl6-IRC-Client#31]
https://github.com/zoffixznet/perl6-IRC-Client/blob/029c43c63b938c991a10cf27eb75907bc6d8623e/lib/IRC/Client.pm6#L270

For example, in [this comment](https://github.com/zoffixznet/perl6-IRC-Client/issues/29#issuecomment-252465320) it was recommended to use ``irc_353``, but as far as I can see the actual method name is ``irc-353``.

Unless I misunderstand something, it should be called “irc-n353” or something like that.

**Comment by zoffixznet** [comment]
I guess it tells you how thorough the test suite for this module is 😂

**Comment by AlexDaniel** [comment]
It's not that bad, there are several live test suites running on ``#perl6`` :P

In fact, we have tests for [whateverables](https://github.com/perl6/whateverable), so we test IRC::Client indirectly as well (a bit).

But yes, this:
```diff
-                take 'irc-' ~ $e.command, $event-name;
+                take 'irc-n' ~ $e.command, $event-name;
```

Solves the problem for me. But of course, it needs documentation changes and tests.
