### ISSUE TITLE
Installation fails  

### ISSUE THREAD

**Issue by faraco** [zoffixznet/perl6-IRC-Client#39]
Hi, I recently trying to install this distribution with `zef`, but failed.

So, I forked this repository, and running travis.ci build on the fork. It seems okay, but when I override the default travis build using `zef install .`, it fails. Running test in your repo with `zef test .` also fail. `panda install .` also failed.

It seems, what made it passed the travis build is because of `PERL6LIB=lib prove -v -r --exec=perl6 t/` that is default build command for travis, but both `zef` and `panda` doesn't work.

Here is 2 builds, (I put a text in README.md to trigger a new build)
https://travis-ci.org/faraco/perl6-IRC-Client/builds

**Comment by zoffixznet** [comment]
> but failed

That tells me absolutely nothing. What are the errors?

**Comment by faraco** [comment]
https://travis-ci.org/faraco/perl6-IRC-Client/builds

**Comment by faraco** [comment]
I updated the comment.

**Comment by faraco** [comment]
Well, in case you don't see the full edit.

Hi, I recently trying to install this distribution with zef, but failed.

So, I forked this repository, and running travis.ci build on the fork. It seems okay, but when I override the default travis build using zef install ., it fails. Running test in your repo with zef test . also fail. panda install . also failed.

It seems, what made it passed the travis build is because of PERL6LIB=lib prove -v -r --exec=perl6 t/ that is default build command for travis, but both zef and panda doesn't work.

Here is 2 builds, (I put a text in README.md to trigger a new build)
https://travis-ci.org/faraco/perl6-IRC-Client/builds

**Comment by zoffixznet** [comment]
I see no new information provided.

**Comment by faraco** [comment]
what, are you sure?

**Comment by faraco** [comment]
did you see the link?

**Comment by faraco** [comment]
Okay, panda worked. But zef did not. I updated the build.

**Comment by faraco** [comment]
the third build https://travis-ci.org/faraco/perl6-IRC-Client/jobs/190618837

Sorry, I had to post in new comment. I think updating the comment actually hide them all.

**Comment by faraco** [comment]
what, why? Do I need to post screencap?

**Comment by zoffixznet** [comment]
> what, why?

Because you posted 7 messages already and still haven't provided information for what issues there are with this module. All I see is a link to a failed travis build of your fork with all the error information hidden. And when I manually run the command, it tells me the failure is in Test::META and not in this module...

**Comment by faraco** [comment]
Well, my bad I guess. Someone in IRC said the same about Test::META. So I should --force install it when dealing with zef.

**Comment by zoffixznet** [comment]
Yeah. The majority of the bots on IRC use this module and they seem to work OK.

**Comment by faraco** [comment]
sorry.
